Gf_scool/urls.py
from django.contrib import admin
from django.urls import path, include
from comptes import views as comptes_views
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comptes.urls')),  # Inclure les URL de l'application comptes
    path('', include('paiement_frais.urls')),
    path('api/auth/', include('djoser.urls')),
    path('api/auth/', include('djoser.urls.jwt')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comptes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EcoleViewSet  #CreateUpdateEcoleAPIView,
from .views import LoginAPIView,UserEcoleAPIView, LogoutView,CreateComptableAPIView,ChangePasswordView, UserProfileUpdateView,UserProfileView, CreateEnseignantAPIView,DirecteurDashboardAPIView,CreateDirecteurAPIView, AdminDashboardAPIView,  ComptableDashboardAPIView
router = DefaultRouter()
router.register(r'ecoles', EcoleViewSet)

urlpatterns = [
    path('api/login/', LoginAPIView.as_view(), name='api-login'),
    path('api/dashboard/admin/', AdminDashboardAPIView.as_view(), name='api-admin-dashboard'),
    path('api/dashboard/comptable/', ComptableDashboardAPIView.as_view(), name='api-comptable-dashboard'),
    #path('api/ecole/create/', CreateUpdateEcoleAPIView.as_view(), name='api-create-ecole'),
    #path('api/ecole/update/<int:pk>/', CreateUpdateEcoleAPIView.as_view(), name='api-update-ecole'),
    path('api/directeur/create/', CreateDirecteurAPIView.as_view(), name='api-create-directeur'),
    path('api/dashboard/directeur/', DirecteurDashboardAPIView.as_view(), name='api-directeur-dashboard'),
    path('api/comptable/create/', CreateComptableAPIView.as_view(), name='api-create-comptable'),
    path('api/dashboard/comptable/', ComptableDashboardAPIView.as_view(), name='api-comptable-dashboard'),
    path('api/enseignants/create/', CreateEnseignantAPIView.as_view(), name='create_enseignant'),
    path('api/me/', UserProfileView.as_view(), name='user-profile'),
    path("api/me/update/", UserProfileUpdateView.as_view(), name="update-profile"),
    path("api/me/change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("api/logout/", LogoutView.as_view(), name="logout"),
    path('api/', include(router.urls)),
    path('api/mon-ecole/', UserEcoleAPIView.as_view(), name='user-ecole'),

    
]

paiement_frais/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import AchatFournitureViewSet, FournisseurViewSet

from .views import (
    CreateEleveAPIView, 
    EleveListView,
    EnregistrerPaiementView,
    EleveDetailView,
    TypeFraisScolaireListCreateView,
    TypeFraisListCreateView,
    TypeFraisDetailView,
    EnregistrerPaiementAutresFraisView,
    CreateInscriptionAPIView,
    CreateAnneeScolaireAPIView,
    ListAnneeScolaireAPIView,
    GenererInscriptionsNouvelleAnnee,
    UpdateEleveIdentityView,
    EleveDetailUpdateAPIView,
    ElevesEnOrdreAPIView,
    ListePaiementAutresFraisOrdre,
    TypeFraisListAPIView,
    CarteScolaireAPIView,
    EleveListAllView,
    AjouterAgentAPIView,
    UtilisateursEcoleAPIView,
    ListeAgentsAPIView,
    PaiementSalaireAgentCreateView,
    AgentDetailAPIView,
    EcoleDetailAPIView,
    RapportJournalierAPIView,
    HistoriqueMouvementsAPIView,
    EcoleAPIView,
    PaiementsDeuxJoursSpecifiquesAPIView, 
    PaiementDetailAPIView,
 
    
    

)
router = DefaultRouter()
router.register(r'achats-fournitures', AchatFournitureViewSet, basename='achats-fournitures')
router.register(r'fournisseurs', FournisseurViewSet, basename='fournisseurs')

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/comptable/create-eleve/', CreateEleveAPIView.as_view(), name='create-eleve'),
    path('api/eleves/', EleveListView.as_view(), name='eleve-list'),
    path('api/paiements/', EnregistrerPaiementView.as_view(), name='enregistrer-paiement'),
    path('api/eleves/<int:id>/', EleveDetailView.as_view(), name='eleve-detail'),
    path('api/eleves/all/', EleveListAllView.as_view(), name='eleve-list-all'),
    path('api/ecoles/<int:id>/', EcoleDetailAPIView.as_view(), name='ecole-detail'),
    path('api/ecole/', EcoleAPIView.as_view(), name='ecole-api'),


    # Frais scolaire
    path('api/type-frais-scolaire/', TypeFraisScolaireListCreateView.as_view(), name='type-frais-list-create'),
    path('api/autres-frais/', TypeFraisListCreateView.as_view(), name='autres-frais'),
    path('type-frais/<int:pk>/', TypeFraisDetailView.as_view(), name='type-frais-detail'),
    path('api/paiement-autres-frais/', EnregistrerPaiementAutresFraisView.as_view(), name='paiement-autres-frais'),
    path('api/inscriptions/', CreateInscriptionAPIView.as_view(), name='create-inscription'),
    path('api/annees-scolaires/create/', CreateAnneeScolaireAPIView.as_view()),
    path("api/annees-scolaires/", ListAnneeScolaireAPIView.as_view()),
    path('api/generer-inscriptions/', GenererInscriptionsNouvelleAnnee.as_view(), name='generer-inscriptions'),  
    path('api/eleves/<int:pk>/', EleveDetailUpdateAPIView.as_view(), name='eleve-detail'),
    path("api/eleves/<int:pk>/identite/", UpdateEleveIdentityView.as_view(), name="update_eleve_identite"),
    path('api/eleves-en-ordre/', ElevesEnOrdreAPIView.as_view(), name='eleves_en_ordre'),
    path('api/liste-autres-frais/', ListePaiementAutresFraisOrdre.as_view(), name='liste_autres_frais'),
    path('api/type-frais-list/', TypeFraisListAPIView.as_view(), name='type-frais-list'),
    ################################## Carte d'eleve ########################################
    path('api/generate-carte/', CarteScolaireAPIView.as_view(), name='generate_carte'),
    path('api/agents/ajouter/', AjouterAgentAPIView.as_view(), name='ajouter-agent'),
    path('api/utilisateurs-ecole/', UtilisateursEcoleAPIView.as_view(), name='utilisateurs_ecole'),
    path('api/agents/', ListeAgentsAPIView.as_view(), name='api_agents'),
    path('api/paiements-salaire/', PaiementSalaireAgentCreateView.as_view(), name='create_paiement_salaire'),
    path('api/agents/<int:id>/', AgentDetailAPIView.as_view(), name='agent-detail'),
    path('api/rapport-journalier/', RapportJournalierAPIView.as_view(), name='rapport-journalier'),
    path('api/historique-mouvements/', HistoriqueMouvementsAPIView.as_view(), name='historique-mouvements'),
    path('api/paiements-hier-aujourdhui/', PaiementsDeuxJoursSpecifiquesAPIView.as_view()),
    path('api/paiement/<int:id>/', PaiementDetailAPIView.as_view()),  # pour modifier un paiement
 ]

paiement_frais/models.py
from django.db import models
import random
import string
import datetime
from django.utils import timezone
from django.db.models import Sum
from paiement_frais.archiving import archiver_mouvement_financier
from django.core.exceptions import ValidationError
from comptes.models import Ecole, User  # Assurez-vous d'importer le modèle Ecole
from django.db import models
from django.core.exceptions import ValidationError
import random
import string

class Eleve(models.Model):
    OPTIONS = [
        ('maternelle', 'Maternelle'),
        ('primaire', 'Primaire'),
        ('education_de_base', 'Éducation de Base'),
        ('pedagogie', 'Pédagogie'),
        ('litteraire', 'Littéraire'),
        ('commerciale_gestion', 'Commerciale et Gestion'),
        ('humanite_sciences', 'Humanité Sciences'),
        ('coupe_couture', 'Coupe et Couture'),
        ('mecanique', 'Mécanique'),
        ('hotellerie_restauration', 'Hôtellerie et Restauration'),
        ('electricite', 'Électricité'),
        ('electronique', 'Électronique'),
    ]

    CLASSES = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
    ]

    SEXE_CHOICES = [
        ('M', 'Masculin'),
        ('F', 'Féminin'),
    ]

    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)
    nom_elev = models.CharField(max_length=100)
    postnom_elev = models.CharField(max_length=100)
    prenom_elev = models.CharField(max_length=100)
    sexe = models.CharField(max_length=1, choices=SEXE_CHOICES, default='M')  # ✅ ajouté
    adresses = models.CharField(max_length=255, blank=True)  # ✅ ajouté
    matricule_elev = models.CharField(max_length=6, unique=True, blank=True)
    date_naissance_elev = models.DateField()
    lieu_naissance_elev = models.CharField(max_length=255)
    option_elev = models.CharField(max_length=100, choices=OPTIONS)
    classe_elev = models.CharField(max_length=2, choices=CLASSES)
    numero_parent1 = models.CharField(max_length=15)
    numero_parent2 = models.CharField(max_length=15, blank=True)

    def save(self, *args, **kwargs):
        if not self.matricule_elev:
            self.matricule_elev = self.generate_unique_matricule()
        super().save(*args, **kwargs)

    def generate_unique_matricule(self):
        while True:
            matricule = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
            if not Eleve.objects.filter(matricule_elev=matricule).exists():
                return matricule

    def clean(self):
        if Eleve.objects.filter(
            nom_elev=self.nom_elev,
            postnom_elev=self.postnom_elev,
            prenom_elev=self.prenom_elev,
            option_elev=self.option_elev,
            classe_elev=self.classe_elev
        ).exclude(id=self.id).exists():
            raise ValidationError("Un élève avec les mêmes nom, postnom, prénom, option et classe existe déjà.")

    def __str__(self):
        return f'{self.nom_elev} {self.postnom_elev} {self.prenom_elev}'

################################# rapport financier,analyse des tendance#######################

class TypeFraisScolaire(models.Model):
    option = models.CharField(max_length=100)
    classe = models.CharField(max_length=50)
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()

    class Meta:
        unique_together = ('option', 'classe', 'ecole')  # ✅ empêche les doublons

    def __str__(self):
        return f"{self.option} - {self.classe} ({self.ecole.nom})"

class Paiement(models.Model):
    eleve = models.ForeignKey('Eleve', on_delete=models.CASCADE)
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)  # Nouvelle clé étrangère
    matricule = models.CharField(max_length=6)
    montant_payer = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    montant_total_payer = models.DecimalField(max_digits=10, decimal_places=2)
    montant_total_a_payer = models.DecimalField(max_digits=10, decimal_places=2)
    montant_restant = models.DecimalField(max_digits=10, decimal_places=2)
    motif_paiement = models.CharField(max_length=255)
    autres_frais_elev = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        super(Paiement, self).save(*args, **kwargs)
        archiver_mouvement_financier(self, self.ecole)
############################################## paiement autres frais ########################
class TypeFrais(models.Model):
    nom = models.CharField(max_length=100)
    montant_total_a_payer = models.DecimalField(max_digits=10, decimal_places=2)
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)

    def __str__(self):
        return self.nom

class PaiementAutresFrais(models.Model):
    eleve = models.ForeignKey('Eleve', on_delete=models.CASCADE)
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)  # Nouvelle clé étrangère
    montant_payer_af = models.DecimalField(max_digits=10, decimal_places=2)
    type_de_frais = models.ForeignKey('TypeFrais', on_delete=models.CASCADE)
    date_payement = models.DateTimeField(auto_now_add=True)
    total_montant_payer_af = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    montant_restant_af = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        # Calcul du montant total payé et restant
        montant_total_a_payer = self.type_de_frais.montant_total_a_payer
        existing_payments = PaiementAutresFrais.objects.filter(eleve=self.eleve, type_de_frais=self.type_de_frais).exclude(id=self.id)
        total_paye = existing_payments.aggregate(Sum('montant_payer_af'))['montant_payer_af__sum'] or 0
        self.total_montant_payer_af = total_paye + self.montant_payer_af
        self.montant_restant_af = montant_total_a_payer - self.total_montant_payer_af

        super(PaiementAutresFrais, self).save(*args, **kwargs)
        archiver_mouvement_financier(self, self.ecole)
################################### pour enregistrer un nouvel agent ###########################
class Agent(models.Model):
    SEXE_CHOICES = [
        ('M', 'Masculin'),
        ('F', 'Féminin'),
    ]
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)  # Nouvelle clé étrangère
    nom_agent = models.CharField(max_length=100)
    postnom_agent = models.CharField(max_length=100)
    prenom_agent = models.CharField(max_length=100)
    sexe_agent = models.CharField(max_length=1, choices=SEXE_CHOICES)
    date_naissance_agent = models.DateField(null=True, blank=True)
    matricule_agent = models.CharField(max_length=8, unique=True, editable=False)
    fonction_agent = models.CharField(max_length=100)
    adresse_agent = models.CharField(max_length=255)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="agent_profile")
    salaire_total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)  # Nouveau champ pour le salaire total
    telephone_agent1 = models.CharField(max_length=15)
    telephone_agent2 = models.CharField(max_length=15, blank=True, null=True)
    cours_dispenser = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.matricule_agent:
            self.matricule_agent = self.generate_matricule()
        super().save(*args, **kwargs)

    @staticmethod
    def generate_matricule():
        letters = ''.join(random.choices(string.ascii_uppercase, k=4))
        digits = ''.join(random.choices(string.digits, k=4))
        matricule = ''.join(random.sample(letters + digits, 8))
        return matricule

    def __str__(self):
        return f'{self.nom_agent} {self.postnom_agent} {self.prenom_agent}'

##################################################################################################
############################### models pour le paiement de salaires ###############################
class PaiementSalaireAgent(models.Model):
    agent = models.ForeignKey('Agent', on_delete=models.CASCADE, related_name='paiements')
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)
    montant_paye = models.DecimalField(max_digits=10, decimal_places=2)
    montant_restant = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    date_paiement = models.DateField(default=datetime.date.today)
    periode = models.CharField(max_length=20)
    motif_paiement = models.TextField(blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculer le montant restant dans la méthode save
        if self.agent:
            total_paye_periode = PaiementSalaireAgent.objects.filter(
                agent=self.agent, periode=self.periode).aggregate(total=models.Sum('montant_paye'))['total'] or 0
            salaire_total = self.agent.salaire_total  # Assurez-vous que salaire_total est défini dans le modèle Agent
            self.montant_restant = salaire_total - (total_paye_periode + self.montant_paye)
            if self.montant_restant < 0:
                raise ValueError(f"Le montant payé pour la période {self.periode} dépasse le salaire total.")
        super(PaiementSalaireAgent, self).save(*args, **kwargs)

##########################################################################################################
###########################" concerne les achats de fournitures #########################################
class Fournisseur(models.Model):
    ecole = models.ForeignKey(Ecole, on_delete=models.CASCADE)  # Nouvelle clé étrangère
    nom = models.CharField(max_length=255)
    contact = models.CharField(max_length=255, blank=True, null=True)
    adresse = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.nom

class AchatFourniture(models.Model):

comptes/templates/paiement_frais/depense/agent_form.html
{% extends "base.html" %}

{% block title %}Ajouter un Agent{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form_styles.css' %}">

<div class="container mt-5">
    <div class="card shadow-lg rounded-lg border-0">
        <div class="card-header text-center bg-primary text-white rounded-top d-flex justify-content-between align-items-center">
            <div class="d-flex">
                <a href="{% url 'home' %}" class="btn btn-light me-2">Accueil</a>
                <a href="{% url 'agent_list' %}" class="btn btn-light">Liste des Agents</a>
            </div>
            <h2 class="highlighted-heading mb-0">Ajouter un Agent</h2>
        </div>
        <div class="card-body">
            <form method="post" novalidate>
                {% csrf_token %}

                <div class="form-group">
                    <label for="{{ form.nom_agent.id_for_label }}">Nom</label>
                    {{ form.nom_agent }}
                    {% if form.nom_agent.errors %}
                        <div class="form-error">{{ form.nom_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.postnom_agent.id_for_label }}">Postnom</label>
                    {{ form.postnom_agent }}
                    {% if form.postnom_agent.errors %}
                        <div class="form-error">{{ form.postnom_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.prenom_agent.id_for_label }}">Prénom</label>
                    {{ form.prenom_agent }}
                    {% if form.prenom_agent.errors %}
                        <div class="form-error">{{ form.prenom_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.sexe_agent.id_for_label }}">Sexe</label>
                    {{ form.sexe_agent }}
                    {% if form.sexe_agent.errors %}
                        <div class="form-error">{{ form.sexe_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.date_naissance_agent.id_for_label }}">Date de Naissance</label>
                    {{ form.date_naissance_agent }}
                    {% if form.date_naissance_agent.errors %}
                        <div class="form-error">{{ form.date_naissance_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.fonction_agent.id_for_label }}">Fonction</label>
                    {{ form.fonction_agent }}
                    {% if form.fonction_agent.errors %}
                        <div class="form-error">{{ form.fonction_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.adresse_agent.id_for_label }}">Adresse</label>
                    {{ form.adresse_agent }}
                    {% if form.adresse_agent.errors %}
                        <div class="form-error">{{ form.adresse_agent.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.telephone_agent1.id_for_label }}">Téléphone 1</label>
                    {{ form.telephone_agent1 }}
                    {% if form.telephone_agent1.errors %}
                        <div class="form-error">{{ form.telephone_agent1.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.telephone_agent2.id_for_label }}">Téléphone 2</label>
                    {{ form.telephone_agent2 }}
                    {% if form.telephone_agent2.errors %}
                        <div class="form-error">{{ form.telephone_agent2.errors }}</div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{ form.cours_dispenser.id_for_label }}">Cours Dispensé</label>
                    {{ form.cours_dispenser }}
                    {% if form.cours_dispenser.errors %}
                        <div class="form-error">{{ form.cours_dispenser.errors }}</div>
                    {% endif %}
                </div>

                <button type="submit" class="btn btn-primary btn-lg btn-block">Enregistrer</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'js/agent_form.js' %}"></script>
{% endblock %}

comptes/templates/paiement_frais/depense/agent_list.html
{% extends "base.html" %}

{% block title %}Liste des Agents{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/agent_list.css' %}">

<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header">
            <h2 class="highlighted-heading mb-0">Liste des Agents</h2>
        </div>
        <div class="card-body">
            <a href="{% url 'create_agent' %}" class="btn btn-primary mb-3">
                <i class="fas fa-plus"></i> Ajouter un Agent
            </a>
            <div class="table-responsive"> <!-- Ajouté pour la réactivité -->
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nom</th>
                            <th>Postnom</th>
                            <th>Prénom</th>
                            <th>Sexe</th>
                            <th>Matricule</th>
                            <th>Fonction</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for agent in agents %}
                        <tr>
                            <td>{{ agent.id }}</td>
                            <td>{{ agent.nom_agent }}</td>
                            <td>{{ agent.postnom_agent }}</td>
                            <td>{{ agent.prenom_agent }}</td>
                            <td>{{ agent.get_sexe_agent_display }}</td>
                            <td>{{ agent.matricule_agent }}</td>
                            <td>{{ agent.fonction_agent }}</td>
                            <td>
                                <a href="{% url 'payer_paiement' agent.pk %}" class="btn btn-primary">Payer</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script src="{% static 'js/agent_list.js' %}"></script>
{% endblock %}

comptes/templates/paiement_frais/depense/agent_paiements_list.html
{% extends "base.html" %}

{% block title %}Liste des Paiements des Agents{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Liste des Paiements des Agents</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Postnom</th>
                <th>Prénom</th>
                <th>Montant Payé</th>
                <th>Date du Paiement</th>
                <th>Période</th>
                <th>Motif du Paiement</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for paiement in paiements %}
            <tr>
                <td>{{ paiement.agent.nom_agent }}</td>
                <td>{{ paiement.agent.postnom_agent }}</td>
                <td>{{ paiement.agent.prenom_agent }}</td>
                <td>{{ paiement.montant_paye }}</td>
                <td>{{ paiement.date_paiement }}</td>
                <td>{{ paiement.periode }}</td>
                <td>{{ paiement.motif_paiement }}</td>
                <td>
                    <a href="{% url 'recu_paiement' paiement.id %}" class="btn btn-primary">Imprimer</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

comptes/templates/paiement_frais/depense/ajouter_paiement.html
{% extends "base.html" %}

{% block title %}Ajouter un Paiement{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form_styles.css' %}">

<div class="container mt-5">
    <div class="d-flex justify-content-between mb-3">
        <button type="button" class="btn btn-danger" onclick="location.href=#">Supprimer Paiement</button>
        <button type="button" class="btn btn-secondary" onclick="location.href='{% url 'liste_paiements' %}'">Lister Paiements</button>
        <button type="button" class="btn btn-success" onclick="window.print();">Imprimer</button>
    </div>
    <div class="card shadow-lg rounded-lg border-0">
        <div class="card-header text-center bg-primary text-white rounded-top">
            <h2 class="highlighted-heading mb-0">Ajouter un Paiement</h2>
        </div>
        <div class="card-body">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary btn-lg btn-block">Enregistrer</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

comptes/templates/paiement_frais/depense/home.html
{% extends "base.html" %}

{% block title %}Page d'Accueil{% endblock %}

{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <div class="menu-container">
        <h1 class="highlighted-heading">Bienvenue sur la Gestion des Dépenses</h1>
        <div class="menu-items">
            <div class="menu-item">
                <a href="{% url 'create_agent' %}">
                    <div class="icon">&#128100;</div>
                    <div class="text">Enregistrement Enseignant</div>
                </a>
            </div>
            <div class="menu-item">
                <a href="{% url 'agent_list' %}">
                    <div class="icon">&#128179;</div>
                    <div class="text">Salaire Enseignant</div>
                </a>
            </div>
            <div class="menu-item">
                <a href="{% url 'creer_achat' %}">
                    <div class="icon">&#128176;</div>
                    <div class="text">Achat Fournitures ou Autres Dépenses</div>
                </a>
            </div>
            <div class="menu-item">
                <a href="#">
                    <div class="icon">&#128295;</div>
                    <div class="text">Dépense Maintenance</div>
                </a>
            </div>
            <div class="menu-item">
                <a href="#">
                    <div class="icon">&#128196;</div>
                    <div class="text">Catégories de Dépense</div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

comptes/templates/paiement_frais/depense/payer_paiement.html
{% extends "base.html" %}

{% block title %}Payer {{ agent.nom_agent }}{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Payer {{ agent.nom_agent }} {{ agent.postnom_agent }} {{ agent.prenom_agent }}</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Confirmer le Paiement</button>
    </form>
</div>
{% endblock %}